name: Puppeteer Script

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Puppeteer script
        run: node script.js
